plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.25'
    id 'com.github.johnrengelman.shadow' version '8.0.0'
    id 'maven-publish'
}

group = 'dev.sora.relay'
version = '1.4.0'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://repo.opencollab.dev/main' }
    maven { url = 'https://repo.opencollab.dev/maven-releases/' }
    maven { url = 'https://repo.opencollab.dev/maven-snapshots/' }
}

configurations {
    embed
    implementation.extendsFrom(embed)
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2")

    embed 'org.cloudburstmc.protocol:bedrock-connection:3.0.0.Beta13-20260917.001841-27'

    // modern codec serializers log via slf4j
    embed 'org.slf4j:slf4j-simple:2.0.13'

    embed 'com.google.code.gson:gson:2.10.1'
    embed project(':msftauth')
    embed 'com.hivemc.leveldb:leveldb:1.1.0'
       embed 'com.hivemc.leveldb:leveldb-api:1.1.0'
    embed('com.squareup.okhttp3:okhttp:4.11.0') {
        exclude group: 'org.jetbrains.kotlin'
    }
}

kotlin {
    jvmToolchain(21)
}

shadowJar {
    archiveClassifier.set('')
    configurations = [project.configurations.embed]
    duplicatesStrategy DuplicatesStrategy.EXCLUDE
}

publishing {
    publications {
        shadow(MavenPublication) { publication ->
            project.shadow.component(publication)
        }
    }
}
